apiVersion: v1
kind: Namespace
metadata:
  name: hello-world-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-service-deployment
  namespace: hello-world-services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-service
  template:
    metadata:
      labels:
        app: hello-world-service
    spec:
      containers:
      - name: hello-world-service
        image: 381492243289.dkr.ecr.eu-west-1.amazonaws.com/hello-world-service:latest
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hello-world-service-hpa
  namespace: hello-world-services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-world-service-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: v1 
kind: Service 
metadata:
  name: hello-world-service
  namespace: hello-world-services
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: hello-world-service
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-service-ingress
  namespace: hello-world-services
spec:
  rules:
  - host: hello-world-service.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service: 
            name: hello-world-service
            port: 
              number: 80