name: Test and ECR

on:
  workflow_dispatch:
  push:
    paths:
      - 'application/**'

jobs:
  build-and-push:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "eu-west-1"

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set unique tag
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "DOCKER_TAG=$(git rev-parse --short=7 "${{ github.sha }}")" >> $GITHUB_ENV
        else
          echo "Tagging not required as this is not test or main push"
        fi

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      run: |
        cd application 
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$DOCKER_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$DOCKER_TAG

    - name: Deploy application to EKS
      run: |
        curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.28.5/2024-01-04/bin/linux/amd64/kubectl
        chmod +x ./kubectl && mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
        aws eks --region eu-west-1 update-kubeconfig --name qa-eks-test
        cd application/eks_templates/

        